spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true



